export enum Brand {
  Apple,
  Samsung,
  Google,
  Xiaomi,
  Oppo,
  Huawei,
}

export enum Camera {
  Notch,
  DynamicIsland,
  Center,
  Left,
  Right,
  Outside,
  Unknown,
}

export enum Type {
  Phone,
  Tablet,
}

export interface Device {
  id: string
  name: string
  width: number
  height: number
  size: number
  density: number // In Pixels per Inch (ppi)
  scale: number
  brand: Brand
  camera: Camera
  type: Type
}

export const deviceSizes: Record<string, Device> = {
  // Apple
  iphone14: {
    id: 'iphone14',
    name: 'iPhone 14',
    width: 1170,
    height: 2532,
    size: 6.1,
    density: 460,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.Notch,
    type: Type.Phone,
  },
  iphone14plus: {
    id: 'iphone14plus',
    name: 'iPhone 14 Plus',
    width: 1284,
    height: 2778,
    size: 6.7,
    density: 458,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.Notch,
    type: Type.Phone,
  },
  iphone14pro: {
    id: 'iphone14pro',
    name: 'iPhone 14 Pro',
    width: 1179,
    height: 2556,
    size: 6.1,
    density: 460,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.DynamicIsland,
    type: Type.Phone,
  },
  iphone14promax: {
    id: 'iphone14promax',
    name: 'iPhone 14 Pro Max',
    width: 1290,
    height: 2796,
    size: 6.7,
    density: 460,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.DynamicIsland,
    type: Type.Phone,
  },
  iphonese3: {
    id: 'iphonese3',
    name: 'iPhone SE 3rd gen',
    width: 750,
    height: 1334,
    size: 4.7,
    density: 326,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Phone,
  },
  iphone13: {
    id: 'iphone13',
    name: 'iPhone 13',
    width: 1170,
    height: 2532,
    size: 6.06,
    density: 460,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.Notch,
    type: Type.Phone,
  },
  iphone13mini: {
    id: 'iphone13mini',
    name: 'iPhone 13 mini',
    width: 1080,
    height: 2340,
    size: 5.42,
    density: 476,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.Notch,
    type: Type.Phone,
  },
  iphone13pro: {
    id: 'iphone13pro',
    name: 'iPhone 13 Pro',
    width: 1170,
    height: 2532,
    size: 6.06,
    density: 460,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.Notch,
    type: Type.Phone,
  },
  iphone13promax: {
    id: 'iphone13promax',
    name: 'iPhone 13 Pro Max',
    width: 1284,
    height: 2778,
    size: 6.68,
    density: 458,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.Notch,
    type: Type.Phone,
  },
  iphone12: {
    id: 'iphone12',
    name: 'iPhone 12',
    width: 1170,
    height: 2532,
    size: 6.06,
    density: 460,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.Unknown,
    type: Type.Phone,
  },
  iphone12mini: {
    id: 'iphone12mini',
    name: 'iPhone 12 mini',
    width: 1080,
    height: 2340,
    size: 5.42,
    density: 476,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.Unknown,
    type: Type.Phone,
  },
  iphone12pro: {
    id: 'iphone12pro',
    name: 'iPhone 12 Pro',
    width: 1170,
    height: 2532,
    size: 6.06,
    density: 460,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.Unknown,
    type: Type.Phone,
  },
  iphone12promax: {
    id: 'iphone12promax',
    name: 'iPhone 12 Pro Max',
    width: 1284,
    height: 2778,
    size: 6.68,
    density: 458,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.Unknown,
    type: Type.Phone,
  },
  iphonese2: {
    id: 'iphonese2',
    name: 'iPhone SE 2nd gen',
    width: 750,
    height: 1334,
    size: 4.7,
    density: 326,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Unknown,
    type: Type.Phone,
  },
  iphone11: {
    id: 'iphone11',
    name: 'iPhone 11',
    width: 828,
    height: 1792,
    size: 6.1,
    density: 326,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Unknown,
    type: Type.Phone,
  },
  iphone11pro: {
    id: 'iphone11pro',
    name: 'iPhone 11 Pro',
    width: 1125,
    height: 2436,
    size: 5.85,
    density: 458,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.Unknown,
    type: Type.Phone,
  },
  iphone11promax: {
    id: 'iphone11promax',
    name: 'iPhone 11 Pro Max',
    width: 1242,
    height: 2688,
    size: 6.46,
    density: 458,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.Unknown,
    type: Type.Phone,
  },
  iphonexr: {
    id: 'iphonexr',
    name: 'iPhone XR',
    width: 828,
    height: 1792,
    size: 6.06,
    density: 326,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Notch,
    type: Type.Phone,
  },
  iphonexsmax: {
    id: 'iphonexsmax',
    name: 'iPhone XS Max',
    width: 1242,
    height: 2688,
    size: 6.46,
    density: 458,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.Notch,
    type: Type.Phone,
  },
  iphonexs: {
    id: 'iphonexs',
    name: 'iPhone XS',
    width: 1125,
    height: 2436,
    size: 5.85,
    density: 458,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.Notch,
    type: Type.Phone,
  },
  iphonex: {
    id: 'iphonex',
    name: 'iPhone X',
    width: 1125,
    height: 2436,
    size: 5.85,
    density: 458,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.Notch,
    type: Type.Phone,
  },
  iphone8plus: {
    id: 'iphone8plus',
    name: 'iPhone 8 Plus',
    width: 1080,
    height: 1920,
    size: 5.5,
    density: 401,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Phone,
  },
  iphone8: {
    id: 'iphone8',
    name: 'iPhone 8',
    width: 750,
    height: 1334,
    size: 4.7,
    density: 326,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Phone,
  },
  iphone7plus: {
    id: 'iphone7plus',
    name: 'iPhone 7 Plus',
    width: 1080,
    height: 1920,
    size: 5.5,
    density: 401,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Phone,
  },
  iphone7: {
    id: 'iphone7',
    name: 'iPhone 7',
    width: 750,
    height: 1334,
    size: 4.7,
    density: 326,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Phone,
  },
  iphonese: {
    id: 'iphonese',
    name: 'iPhone SE 1st gen',
    width: 640,
    height: 1136,
    size: 4,
    density: 326,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Phone,
  },
  iphone6splus: {
    id: 'iphone6splus',
    name: 'iPhone 6S Plus',
    width: 1080,
    height: 1920,
    size: 5.5,
    density: 401,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Phone,
  },
  iphone6s: {
    id: 'iphone6s',
    name: 'iPhone 6s',
    width: 750,
    height: 1334,
    size: 4.7,
    density: 326,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Phone,
  },
  iphone6plus: {
    id: 'iphone6plus',
    name: 'iPhone 6 Plus',
    width: 1080,
    height: 1920,
    size: 5.5,
    density: 401,
    scale: 3,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Phone,
  },
  iphone6: {
    id: 'iphone6',
    name: 'iPhone 6',
    width: 750,
    height: 1334,
    size: 4.7,
    density: 326,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Phone,
  },
  iphone5c: {
    id: 'iphone5c',
    name: 'iPhone 5C',
    width: 640,
    height: 1136,
    size: 4,
    density: 326,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Phone,
  },
  iphone5s: {
    id: 'iphone5s',
    name: 'iPhone 5S',
    width: 640,
    height: 1136,
    size: 4,
    density: 326,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Phone,
  },
  iphone5: {
    id: 'iphone5',
    name: 'iPhone 5',
    width: 640,
    height: 1136,
    size: 4,
    density: 326,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Phone,
  },
  iphone4s: {
    id: 'iphone4s',
    name: 'iPhone 4S',
    width: 640,
    height: 960,
    size: 3.5,
    density: 326,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Phone,
  },
  iphone4: {
    id: 'iphone4',
    name: 'iPhone 4',
    width: 640,
    height: 960,
    size: 3.5,
    density: 326,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Phone,
  },
  iphone3gs: {
    id: 'iphone3gs',
    name: 'iPhone 3GS',
    width: 320,
    height: 480,
    size: 3.5,
    density: 163,
    scale: 1,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Phone,
  },
  iphone3g: {
    id: 'iphone3g',
    name: 'iPhone 3G',
    width: 320,
    height: 480,
    size: 3.5,
    density: 163,
    scale: 1,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Phone,
  },
  iphone: {
    id: 'iphone',
    name: 'iPhone',
    width: 320,
    height: 480,
    size: 3.5,
    density: 163,
    scale: 1,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Phone,
  },
  ipadair5: {
    id: 'ipadair5',
    name: 'iPad Air (5th gen)',
    width: 1640,
    height: 2360,
    size: 10.9,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadmini6: {
    id: 'ipadmini6',
    name: 'iPad Mini (6th gen)',
    width: 1488,
    height: 2266,
    size: 8.3,
    density: 326,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipad9: {
    id: 'ipad9',
    name: 'iPad 9th gen',
    width: 1620,
    height: 2160,
    size: 10.2,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadpro5_13: {
    id: 'ipadpro5_13',
    name: 'iPad Pro (5th gen 12.9")',
    width: 2048,
    height: 2732,
    size: 12.9,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadpro5_11: {
    id: 'ipadpro5_11',
    name: 'iPad Pro (5th gen 11")',
    width: 1668,
    height: 2388,
    size: 11,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadair4: {
    id: 'ipadair4',
    name: 'iPad Air (4th gen)',
    width: 1640,
    height: 2360,
    size: 10.9,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipad8: {
    id: 'ipad8',
    name: 'iPad 8th gen',
    width: 1620,
    height: 2160,
    size: 10.2,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadpro4_13: {
    id: 'ipadpro4_13',
    name: 'iPad Pro (4th gen 12.9")',
    width: 2048,
    height: 2732,
    size: 12.9,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadpro4_11: {
    id: 'ipadpro4_11',
    name: 'iPad Pro (4th gen 11")',
    width: 1668,
    height: 2388,
    size: 11,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipad7: {
    id: 'ipad7',
    name: 'iPad 7th gen',
    width: 1620,
    height: 2160,
    size: 10.2,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadmini5: {
    id: 'ipadmini5',
    name: 'iPad Mini (5th gen)',
    width: 1536,
    height: 2048,
    size: 7.9,
    density: 326,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadair3: {
    id: 'ipadair3',
    name: 'iPad Air (3rd gen)',
    width: 1668,
    height: 2224,
    size: 10.5,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadpro3_13: {
    id: 'ipadpro3_13',
    name: 'iPad Pro (3rd gen 12.9")',
    width: 2048,
    height: 2732,
    size: 12.9,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadpro3_11: {
    id: 'ipadpro3_11',
    name: 'iPad Pro (3rd gen 11")',
    width: 1668,
    height: 2388,
    size: 11,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipad6: {
    id: 'ipad6',
    name: 'iPad 6th gen',
    width: 1536,
    height: 2048,
    size: 9.7,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadpro2_13: {
    id: 'ipadpro2_13',
    name: 'iPad Pro (2nd gen 12.9")',
    width: 2048,
    height: 2732,
    size: 12.9,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadpro2_11: {
    id: 'ipadpro2_11',
    name: 'iPad Pro (2nd gen 10.5")',
    width: 1668,
    height: 2224,
    size: 10.5,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipad5: {
    id: 'ipad5',
    name: 'iPad 5th gen',
    width: 1536,
    height: 2048,
    size: 9.7,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadpro_10: {
    id: 'ipadpro_10',
    name: 'iPad Pro (1st gen 9.7”)',
    width: 1536,
    height: 2048,
    size: 9.7,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadpro_13: {
    id: 'ipadpro_13',
    name: 'iPad Pro (1st gen 12.9")',
    width: 2048,
    height: 2732,
    size: 12.9,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadmini4: {
    id: 'ipadmini4',
    name: 'iPad mini 4',
    width: 1536,
    height: 2048,
    size: 7.9,
    density: 326,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadair2: {
    id: 'ipadair2',
    name: 'iPad Air 2',
    width: 1536,
    height: 2048,
    size: 9.7,
    density: 326,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadmini3: {
    id: 'ipadmini3',
    name: 'iPad mini 3',
    width: 1536,
    height: 2048,
    size: 7.9,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadmini2: {
    id: 'ipadmini2',
    name: 'iPad mini 2',
    width: 1536,
    height: 2048,
    size: 7.9,
    density: 326,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadair: {
    id: 'ipadair',
    name: 'iPad Air',
    width: 1536,
    height: 2048,
    size: 9.7,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipad4: {
    id: 'ipad4',
    name: 'iPad 4th gen',
    width: 1536,
    height: 2048,
    size: 9.7,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipadmini: {
    id: 'ipadmini',
    name: 'iPad mini',
    width: 768,
    height: 1024,
    size: 7.9,
    density: 163,
    scale: 1,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipad3: {
    id: 'ipad3',
    name: 'iPad 3rd gen',
    width: 1536,
    height: 2048,
    size: 9.7,
    density: 264,
    scale: 2,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipad2: {
    id: 'ipad2',
    name: 'iPad 2',
    width: 768,
    height: 1024,
    size: 9.7,
    density: 132,
    scale: 1,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  ipad: {
    id: 'ipad',
    name: 'iPad',
    width: 768,
    height: 1024,
    size: 9.7,
    density: 132,
    scale: 1,
    brand: Brand.Apple,
    camera: Camera.Outside,
    type: Type.Tablet,
  },
  // Google
  pixel7: {
    id: 'pixel7',
    name: 'Google Pixel 7',
    width: 1080,
    height: 2400,
    size: 6.3,
    density: 416,
    scale: 3,
    brand: Brand.Google,
    camera: Camera.Unknown,
    type: Type.Phone,
  },
  // Samsung
  galaxys22ultra: {
    id: 'galaxys22ultra',
    name: 'Samsung Galaxy S22 Ultra 5G',
    width: 1440,
    height: 3088,
    size: 6.8,
    density: 500,
    scale: 4,
    brand: Brand.Samsung,
    camera: Camera.Center,
    type: Type.Phone,
  },
  galaxya53: {
    id: 'galaxya53',
    name: 'Samsung Galaxy A53 5G',
    width: 1080,
    height: 2400,
    size: 6.5,
    density: 405,
    scale: 3, // 2.625??
    brand: Brand.Samsung,
    camera: Camera.Center,
    type: Type.Phone,
  },
  // Xiaomi
  redminote9pro: {
    id: 'redminote9pro',
    name: 'Xiaomi Redmi Note 9 Pro',
    width: 1080,
    height: 2400,
    size: 6.67,
    density: 395,
    scale: 3, // ?
    brand: Brand.Xiaomi,
    camera: Camera.Center,
    type: Type.Phone,
  },
  '12t': {
    id: '12t',
    name: 'Xiaomi 12T',
    width: 1220,
    height: 2712,
    size: 6.67,
    density: 446,
    scale: 3, // ?
    brand: Brand.Xiaomi,
    camera: Camera.Center,
    type: Type.Phone,
  },
  '12tpro': {
    id: '12tpro',
    name: 'Xiaomi 12T Pro',
    width: 1220,
    height: 2712,
    size: 6.67,
    density: 446,
    scale: 3, // ?
    brand: Brand.Xiaomi,
    camera: Camera.Center,
    type: Type.Phone,
  },
  // Oppo
  reno8pro: {
    id: 'reno8pro',
    name: 'Oppo Reno8 Pro',
    width: 1080,
    height: 2412,
    size: 6.7,
    density: 394,
    scale: 3, // ?
    brand: Brand.Oppo,
    camera: Camera.Center,
    type: Type.Phone,
  },
  // Huawei
  p9litemini: {
    id: 'p9litemini',
    name: 'Huawei P9 lite mini',
    width: 720,
    height: 1280,
    size: 5,
    density: 294,
    scale: 2, // ?
    brand: Brand.Huawei,
    camera: Camera.Outside,
    type: Type.Phone,
  },
}
